# Generated by Django 5.0.4 on 2026-04-13 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('post_id', models.UUIDField()),
                ('author_id', models.UUIDField()),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'feed_items',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user_id', '-score', '-created_at'], name='feed_items_user_id_717eaa_idx')],
                'unique_together': {('user_id', 'post_id')},
            },
        ),
    ]
