# Generated by Django 5.0.4 on 2026-04-13 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('actor_id', models.UUIDField(null=True)),
                ('type', models.CharField(choices=[('like', 'いいね'), ('comment', 'コメント'), ('follow', 'フォロー'), ('follow_request', 'フォローリクエスト'), ('mention', 'メンション'), ('story_view', 'ストーリーズ閲覧')], max_length=30)),
                ('ref_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx')],
            },
        ),
    ]
