# Generated by Django 5.0.4 on 2026-04-14 00:45

import media_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('media_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('media_type', models.CharField(choices=[('image', '画像'), ('video', '動画')], max_length=10)),
                ('file', models.FileField(upload_to=media_app.models.media_upload_path)),
                ('url', models.CharField(blank=True, max_length=512)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'アップロード待ち'), ('processing', '処理中'), ('ready', '完了'), ('failed', '失敗')], default='ready', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='media_files_user_id_0814ea_idx')],
            },
        ),
    ]
