# Generated by Django 5.0.4 on 2026-04-13 06:57

import django.db.models.deletion
import stories.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('media_url', models.CharField(max_length=512)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(default=stories.models.default_expires_at)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='stories_user_id_b336dc_idx'), models.Index(fields=['expires_at'], name='stories_expires_a4b2b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_id', models.UUIDField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.story')),
            ],
            options={
                'db_table': 'story_views',
                'unique_together': {('story', 'viewer_id')},
            },
        ),
    ]
