# Generated by Django 5.0.4 on 2026-04-14 01:13

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name='HashtagIndex',
            fields=[
                ('hashtag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('post_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_hashtags',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='search_hashtags_name_gin', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('query', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='search_hist_user_id_3ea0ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserIndex',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=150)),
                ('profile_img', models.CharField(blank=True, max_length=512)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('follower_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_users',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['username'], name='search_users_username_gin', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
